Web/RentACar.Web/Areas/Administration/Controllers/VehiclesController.cs
namespace RentACar.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using RentACar.Data;
    using RentACar.Data.Common.Repositories;
    using RentACar.Data.Models;
    using RentACar.Web.Areas.Administration.Services;

    [Area("Administration")]
    public class VehiclesController : Controller
    {
        private readonly IDeletableEntityRepository<Vehicle> dataRepo;
        private readonly IRepository<Facility> facilityRepo;
        private readonly IVehicleAdminService vehicleAdminService;

        public VehiclesController(IDeletableEntityRepository<Vehicle> dataRepo, IRepository<Facility> facilityRepo, IVehicleAdminService vehicleAdminService)
        {
            this.dataRepo = dataRepo;
            this.facilityRepo = facilityRepo;
            this.vehicleAdminService = vehicleAdminService;
        }

        // GET: Administration/Vehicles
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = this.dataRepo.All().Include(v => v.Facility);
            return this.View(await applicationDbContext.ToListAsync());
        }

        // GET: Administration/Vehicles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var vehicle = await this.dataRepo.All()
                .Include(v => v.Facility)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return this.NotFound();
            }

            return this.View(vehicle);
        }

        // GET: Administration/Vehicles/Create
        public IActionResult Create()
        {
            this.ViewData["FacilityId"] = new SelectList(this.facilityRepo.All(), "Id", "Id");
            return this.View();
        }

        // POST: Administration/Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Brand,Model,CoupeType,Seats,RequiredLicenseCategory,FuelType,Gearbox,Doors,YearOfManufacturing,FuelTankVolume,FuelConsumption,TrunkVolume,Horsepower,EngineVolume,IsBooked,PricePerDay,FacilityId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Vehicle vehicle)
        {
            if (this.ModelState.IsValid)
            {
                await this.dataRepo.AddAsync(vehicle);
                await this.dataRepo.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["FacilityId"] = new SelectList(this.facilityRepo.All(), "Id", "Id", vehicle.FacilityId);
            return this.View(vehicle);
        }

        // GET: Administration/Vehicles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var vehicle = await this.dataRepo.All().FirstOrDefaultAsync(x => x.Id == id);
            if (vehicle == null)
            {
                return this.NotFound();
            }

            this.ViewData["FacilityId"] = new SelectList(this.facilityRepo.All(), "Id", "Id", vehicle.FacilityId);
            return this.View(vehicle);
        }

        // POST: Administration/Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Brand,Model,CoupeType,Seats,RequiredLicenseCategory,FuelType,Gearbox,Doors,YearOfManufacturing,FuelTankVolume,FuelConsumption,TrunkVolume,Horsepower,EngineVolume,IsBooked,PricePerDay,FacilityId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.dataRepo.Update(vehicle);
                    await this.dataRepo.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.VehicleExists(vehicle.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["FacilityId"] = new SelectList(this.facilityRepo.All(), "Id", "Id", vehicle.FacilityId);
            return this.View(vehicle);
        }

        // GET: Administration/Vehicles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var vehicle = await this.dataRepo.All()
                .Include(v => v.Facility)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return this.NotFound();
            }

            return this.View(vehicle);
        }

        // POST: Administration/Vehicles/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var delete = await this.vehicleAdminService.Delete(id);

            //var vehicle = await this.dataRepo.All().FirstOrDefaultAsync(x => x.Id == id);
            //this.dataRepo.Delete(vehicle);
            //await this.dataRepo.SaveChangesAsync();

            if (delete == "Success!")
            {
                return this.Redirect("/Administration/Vehicles/Index");
            }
            else
            {
                return this.NotFound();
            }
        }

        private async Task<bool> VehicleExists(string id)
        {
            var result = await this.vehicleAdminService.VehicleExists(id);

            return result;
        }
    }
}

Web/RentACar.Web/Controllers/FacilityController.cs
namespace RentACar.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using RentACar.Services.Data;
    using RentACar.Web.ViewModels.Facility;

    public class FacilityController : Controller
    {
        private readonly IFacilityService facilityService;

        public FacilityController(IFacilityService facilityService)
        {
            this.facilityService = facilityService;
        }

        [Authorize]
        public IActionResult AddFacility()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddFacility(AddNewFacilityViewModel input)
        {
            var facilityID = await this.facilityService.AddFacility(input);

            return this.Redirect("AddFacility");
        }
    }
}

Web/RentACar.Web/Controllers/VehicleController.cs
namespace RentACar.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using RentACar.Services.Data;
    using RentACar.Web.ViewModels.Facility;
    using RentACar.Web.ViewModels.Image;
    using RentACar.Web.ViewModels.Vehicle;

    public class VehicleController : Controller
    {
        private readonly IVehicleService vehicleService;
        private readonly ICloudinaryService cloudinaryService;
        private readonly IFacilityService facilityService;
        private readonly ICommentService commentService;

        public VehicleController(IVehicleService vehicleService, ICloudinaryService cloudinaryService, IFacilityService facilityService, ICommentService commentService)
        {
            this.vehicleService = vehicleService;
            this.cloudinaryService = cloudinaryService;
            this.facilityService = facilityService;
            this.commentService = commentService;
        }

        [Authorize]
        public IActionResult AddVehicle()
        {
            var facilities = this.facilityService.GetAll<FacilityDropDownViewModel>();
            var viewModel = new AddVehicleViewModel
            {
                Facilities = facilities,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> AddVehicle(AddVehicleViewModel input)
        {
            var vehicleID = await this.vehicleService.AddVehicle(input);

            return this.Redirect($"VehicleDetails/{vehicleID}");
        }

        public IActionResult AllVehicles()
        {
            var allVehicles = this.vehicleService.GetAllVehicles<VehicleCardDetailsViewModel>();

            var model = new AllVehiclesViewModel { Vehicles = allVehicles };

            return this.View(model);
        }

        public async Task<IActionResult> VehicleDetails(string id)
        {
            var vehicle = this.vehicleService.GetById(id);

            var comments = await this.commentService.Latest3VehicleComments(id);

            vehicle.LatestComments = comments;

            return this.View(vehicle);
        }
    }
}

Web/RentACar.Web/Views/Shared/_ImageSliderPartial.cshtml
@model RentACar.Web.ViewModels.Vehicle.VehicleDetailsViewModel

@{ 
    var images = Model.Images.Select(x => new SelectListItem(x.URL, x.Id.ToString()));
}


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="margin-right: 55px; width: 400px; float: left;">
    <div class="carousel-inner">
        @foreach (var pic in @Model.Images)
        {
            <div class="carousel-item" id="@pic.Id">
                <img class="d-block w-100" src="@pic.URL" id="@pic.Id" style="height:290px;width: 400px;border-radius: 7px;">
            </div>
        }
    </div>
</div>

Web/RentACar.Web/Views/Shared/_Layout.cshtml
@using RentACar.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Vehicles
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="AddVehicle">Add Vehicle</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="AllVehicles">All Vehicles</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Facilities
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Facility" asp-action="AddFacility">Add Facility</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Facility" asp-action="AllFacilities">All Facilities</a>
                            </div>
                        </li>
                        
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Vehicles" asp-action="Index">Admin Vehicles</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>